### ISSUE TITLE
Firemage Rotation Scorch Issue

### ISSUE THREAD

**Issue by CorsairSailor** [herotc/hero-rotation#491]
First of all, huge thanks for providing such a great addon. It makes adopting new classes or returning to twinks so much easier.
I hope it's not some kind of mistake on my side, but with version 8.0.2.00(Release) of the Hero Rotation Addon, coming from 	8.0.1.12(Release) I started noticing a huge increase in Scorch being recommended, even when common sense and plain numbers do not suggest so. Regular Fireball is suggested rarely to not at all. I tried switching talents, reinstalling, using the alpha build of the addon, but nothing changed that behaviour. Some parts of the rotation(for example casting Meteor after Rune of Power) still work, and the added trinkets and Essences are a welcome addition, but with 90% of the suggested spells being Scorch, this appears to be broken so much, it's unusable for me. 8.0.1.12 worked fine as mentioned and at the moment I'm sticking with this version.
Talents: 3231123 (most times)
Feedback of any kind(especially if the mistake is on my side) would be highly appreciated.

Cheers,

CorsairSailor

**Comment by Cilraaz** [comment]
Scorch is suggested in multiple places.

1. During Combustion as filler
2. During RoP, if Searing Touch is enabled and target is 30% hp or lower
3. During the standard rotation, if Searing Touch is enabled and target is 30% hp or lower
4. During the standard rotation, behind Fireball, as a filler during movement

There was another condition that was suggesting Scorch when Fire Blast should have been suggested, which I just fixed. Please update to the latest alpha to get this change.

If you're still seeing Scorch being suggested outside the above 4 conditions, please enable Debug Output in the addon settings and let me know what your chat box says when it's wrongly suggested. It should say something like "scorch xxx", where xxx is a number.

**Comment by CorsairSailor** [comment]
Thanks for your reply, I'm familiar with the 4 Situations you described, when Scorch is recommended, unfortunatly the problem still exist. I used version: 8.0.2.00-53-g2afcd15-alpha. 

Edit:**In the last section, I found that it's only working weird, when Combustion is not on CD and not running. While combustion is running or on CD, the suggested rotation seems correct to me. Maybe it's working correct now, but with that knowledge the latest version is usable for me again.**

Engaging a big blue WQ Mob at 90% health:
[Hero Rotation] pyroblast 14 
[Hero Rotation] scorch 398 
[Hero Rotation] pyroblast 390 
[Hero Rotation] scorch 398 
[Hero Rotation] pyroblast 390 
[Hero Rotation] pyroblast 330 
[Hero Rotation] scorch 398 
[Hero Rotation] pyroblast 390 
[Hero Rotation] scorch 398 
[Hero Rotation] pyroblast 390 
[Hero Rotation] pyroblast 330 
[Hero Rotation] scorch 398
End of encounter.

Next fight is against a regular blue WQ Mob, with some random RoP, Lucid Dreams and Combustion in between:
[Hero Rotation] scorch 398 
[Hero Rotation] fire_blast 255 
[Hero Rotation] scorch 398 
[Hero Rotation] meteor 32 
[Hero Rotation] scorch 398 
[Hero Rotation] pyroblast 330 
[Hero Rotation] scorch 398 
[Hero Rotation] pyroblast 390 
[Hero Rotation] scorch 247 
[Hero Rotation] pyroblast 330 
[Hero Rotation] scorch 398 
[Hero Rotation] scorch 247 
[Hero Rotation] pyroblast 330 
[Hero Rotation] scorch 398 
[Hero Rotation] scorch 247 
[Hero Rotation] scorch 398 
[Hero Rotation] pyroblast 330 
End of encounter.

Another encounter:
[Hero Rotation] scorch 398 
[Hero Rotation] pyroblast 390 
[Hero Rotation] pyroblast 330 
[Hero Rotation] scorch 398 
[Hero Rotation] pyroblast 390 
[Hero Rotation] scorch 398 
End

Now several small encounters with groups up to 5 mobs:

[Hero Rotation] fire_blast 830 
[Hero Rotation] fireball 784 
[Hero Rotation] fire_blast 830 
[Hero Rotation] fireball 784 
[Hero Rotation] pyroblast 610 
[Hero Rotation] fireball 784 
[Hero Rotation] fire_blast 830 
[Hero Rotation] fire_blast 636 
[Hero Rotation] pyroblast 610 
[Hero Rotation] fireball 784 
[Hero Rotation] fire_blast 636 
[Hero Rotation] pyroblast 610 
[Hero Rotation] scorch 780 
[Hero Rotation] scorch 398 
[Hero Rotation] pyroblast 390 
[Hero Rotation] scorch 398 
[Hero Rotation] pyroblast 390 
[Hero Rotation] pyroblast 330 
[Hero Rotation] scorch 398 
[Hero Rotation] pyroblast 14 
[Hero Rotation] scorch 398 
[Hero Rotation] scorch 247 
[Hero Rotation] scorch 398 
[Hero Rotation] pyroblast 330 
[Hero Rotation] scorch 398 
[Hero Rotation] scorch 247 
[Hero Rotation] pyroblast 330 
[Hero Rotation] scorch 398 
[Hero Rotation] scorch 247 
[Hero Rotation] fire_blast 830 
[Hero Rotation] fireball 784 
[Hero Rotation] fire_blast 636 
[Hero Rotation] pyroblast 610 
[Hero Rotation] scorch 780 
[Hero Rotation] pyroblast 620 
[Hero Rotation] pyroblast 14 
[Hero Rotation] fireball 784 
[Hero Rotation] fire_blast 830 
[Hero Rotation] pyroblast 610 
[Hero Rotation] fireball 784 
[Hero Rotation] fire_blast 636 
[Hero Rotation] pyroblast 620 
[Hero Rotation] pyroblast 610 
[Hero Rotation] scorch 780 
[Hero Rotation] pyroblast 14 
[Hero Rotation] fire_blast 636 
[Hero Rotation] pyroblast 610 
[Hero Rotation] fireball 784 
[Hero Rotation] fire_blast 636 
[Hero Rotation] pyroblast 610 
[Hero Rotation] scorch 780 
[Hero Rotation] fireball 784 
[Hero Rotation] pyroblast 610 
[Hero Rotation] fireball 784 
[Hero Rotation] scorch 398 
[Hero Rotation] pyroblast 390 
[Hero Rotation] pyroblast 330 
[Hero Rotation] scorch 398 
[Hero Rotation] pyroblast 390 
[Hero Rotation] pyroblast 330 
[Hero Rotation] scorch 398 
[Hero Rotation] pyroblast 14 
[Hero Rotation] scorch 398 
[Hero Rotation] pyroblast 390 
[Hero Rotation] pyroblast 330 
[Hero Rotation] scorch 398 
[Hero Rotation] pyroblast 390 
[Hero Rotation] pyroblast 330 
[Hero Rotation] scorch 398 
[Hero Rotation] pyroblast 390 
[Hero Rotation] pyroblast 330 
[Hero Rotation] scorch 398 
[Hero Rotation] scorch 247 
[Hero Rotation] scorch 398 
[Hero Rotation] scorch 247 
[Hero Rotation] pyroblast 330 
[Hero Rotation] scorch 398 
[Hero Rotation] scorch 247 
[Hero Rotation] scorch 398 
[Hero Rotation] pyroblast 330 
[Hero Rotation] scorch 398 
[Hero Rotation] scorch 247 
[Hero Rotation] pyroblast 330 
[Hero Rotation] scorch 398 
[Hero Rotation] pyroblast 330 
[Hero Rotation] dragons_breath 420 
[Hero Rotation] pyroblast 14 
[Hero Rotation] fireball 784 
[Hero Rotation] scorch 780 
[Hero Rotation] pyroblast 726 
[Hero Rotation] scorch 780 
[Hero Rotation] fireball 784 
[Hero Rotation] fire_blast 830 
[Hero Rotation] fireball 784 
[Hero Rotation] pyroblast 610 
[Hero Rotation] fireball 784 
[Hero Rotation] scorch 780 
[Hero Rotation] fireball 784 
[Hero Rotation] pyroblast 610 
[Hero Rotation] fire_blast 830 
[Hero Rotation] scorch 780 
[Hero Rotation] fireball 784 
[Hero Rotation] fire_blast 636 
[Hero Rotation] pyroblast 610 
[Hero Rotation] fireball 784 
[Hero Rotation] fire_blast 636 
[Hero Rotation] pyroblast 610 
[Hero Rotation] fireball 784 
[Hero Rotation] pyroblast 610 
[Hero Rotation] scorch 780 
[Hero Rotation] fire_blast 636 
[Hero Rotation] pyroblast 620 
[Hero Rotation] scorch 780

**Comment by Cilraaz** [comment]
I'm mainly seeing "scorch 398", which is Scorch during Combustion, which is correct. 
I'm also seeing "scorch 780", which is Scorch with Searing Touch when the target is under 30% hp. This is also correct.
The "scorch 247" is an incorrect debug output, as that's the Fire Blast that was previously corrected. I'll correct the debug output.

I'm not seeing the problem here, unfortunately. Perhaps the Fire Blast typo fix from earlier today fixed your issue? If not, please let me know and I can investigate it further.

**Comment by CorsairSailor** [comment]
I understand your points, what I'm trying to say is that everything works fine, while combustion is running or on CD, BUT when it's off CD and not running, it suggests the following from a fight against Ivus the Worldboss. Scorch for so long till it crits(over 30% health), than another followed by pyroblast, although that Scorch before Pyroblast is not guaranteed to crit by any means, so it often results in regular casts of pyroblasts with about 4 seconds cast time or sth. like that. This didn't happen with version 8.0.1.12(Release). In short: Combustion off CD and not running->only Scorch and Pyroblast are suggestions at any health %. Hopefully this clarifies the problem. I used version 8.0.2.00-53-g2afcd15-alpha.

[Hero Rotation] scorch 398 
[Hero Rotation] pyroblast 390 
[Hero Rotation] scorch 398 
[Hero Rotation] pyroblast 390 
[Hero Rotation] pyroblast 330 
[Hero Rotation] scorch 398 
[Hero Rotation] pyroblast 390 
[Hero Rotation] scorch 398 
[Hero Rotation] pyroblast 390 
[Hero Rotation] scorch 398 
[Hero Rotation] pyroblast 390 
[Hero Rotation] scorch 398 
[Hero Rotation] pyroblast 390 
[Hero Rotation] pyroblast 330 
[Hero Rotation] scorch 398 
[Hero Rotation] pyroblast 390 
[Hero Rotation] scorch 398 
[Hero Rotation] pyroblast 390 
[Hero Rotation] scorch 398 
[Hero Rotation] pyroblast 390 
[Hero Rotation] scorch 398

**Comment by CorsairSailor** [comment]
That behaviour is a little disturbing for example, when delaying combustion a little for a DPS Check, Huge Stack of Adds spawning or similiar Phases of a fight, where a lot of Damage is required.

**Comment by Cilraaz** [comment]
The "CombustionPhase" function within the rotation (of which scorch 398 is a part) is called when Combustion is ready or active, not just when it's active. Per the SimC APL:
`call_action_list,name=combustion_phase,if=(talent.rune_of_power.enabled&cooldown.combustion.remains<=action.rune_of_power.cast_time|cooldown.combustion.ready)&!firestarter.active|buff.combustion.up`
I'll look into the possibility of adding some kind of failsafe to suggest Fireball when delaying Combustion, but I don't want to stray too far from the intent of the SimC APL.

**Comment by CorsairSailor** [comment]
Ah, so it's an external change, well okay, I guess it's fine then. Thank you very much for your effort and support.
