### ISSUE TITLE
[Balance Druid] - Keybinds not showing correctly

### ISSUE THREAD

**Issue by RussellAnas** [herotc/hero-rotation#714]
Keybinds are not showing for some spells, and for others, they're not updating when changing keybinds. Would appreciate a fix!

**Comment by Cilraaz** [comment]
What hotbar addon are you using? What spells are not showing a keybind?

**Comment by RussellAnas** [comment]
Not using any hotbar addon, using default wow keybinds. 'Wrath', 'Sunfire', 'Moonfire' etc., all of them don't show updated keybinds. Basically all spells on my balance druid having a problem.
Works fine on my warrior, priest etc.

**Comment by EloneSK** [comment]
please fix the addon, it will only show me the only spell [Wrath] and trinket. I also deleted the Keybinds. You can't play with that addon. Hunter, the Paladin is working normally. The druid is completely wrong.

**Comment by Cilraaz** [comment]
There is no keybind code in the spec profiles. If it works for one spec, it should be working for all specs. I also can't replicate any issue with keybinds not showing for Balance.

**Comment by EloneSK** [comment]
> There is no keybind code in the spec profiles. If it works for one spec, it should be working for all specs. I also can't replicate any issue with keybinds not showing for Balance.

so what is the solution to make the balance work normally?

**Comment by RussellAnas** [comment]
No idea what's the problem, but here are two screenshots for you. If you see, one of the spells is not showing a keybind, the other is showing the wrong keybind
![image](https://user-images.githubusercontent.com/77004545/106481452-46df1e00-64ce-11eb-8dfa-5b59099f3a2b.png)
![image](https://user-images.githubusercontent.com/77004545/106481521-565e6700-64ce-11eb-8043-9451fa23bd55.png)

**Comment by RussellAnas** [comment]
I've tried re-installing the addon, deleting saved variables, and resetting wow keybinds, it's still not working

**Comment by EloneSK** [comment]
as RussellAnas writes, I deleted all the addon saves, I deleted the complete Addons, WDB ,WTS folder in the game and game saves.  I reinstalled Addons and Hero rotation addon and it still shows spell wrath when I start a fight and then. 
I don't understand anything.  
Alternatively, I can attach a screenshot of the game.

**Comment by rmfb** [comment]
@EloneSK 

> please fix the addon, it will only show me the only spell [Wrath] and trinket. I also deleted the Keybinds. You can't play with that addon. Hunter, the Paladin is working normally. The druid is completely wrong.

This sounds like you are not using the correct version of the balance script. You should sync or download the GitHub directory since the alpha package isn’t always posted to curse due to a packaging issues with curseforge. Also, the last time I tried out the balance script it was missing covent spells. It is still listed as wip, so I would rely on it outside of open world questing right now.

**Comment by EloneSK** [comment]
> @EloneSK 
> 
> 
> 
> > please fix the addon, it will only show me the only spell [Wrath] and trinket. I also deleted the Keybinds. You can't play with that addon. Hunter, the Paladin is working normally. The druid is completely wrong.
> 
> 
> 
> This sounds like you are not using the correct version of the balance script. You should sync or download the GitHub directory since the alpha package isn’t always posted to curse due to a packaging issues with curseforge. Also, the last time I tried out the balance script it was missing covent spells. It is still listed as wip, so I would rely on it outside of open world questing right now. 

you were right.  The version on curseforge was bad.  I put a download from GitHub and rewrote the directory and it's getting better.  it doesn't show keybinds but you can play with it.  well thank you

**Comment by EloneSK** [comment]
![dudu](https://user-images.githubusercontent.com/78366434/106510253-fb793f80-64ce-11eb-8fb8-9a345d8c07a8.jpg)

**Comment by Cilraaz** [comment]
I've been able to replicate the issue, but don't have a fix for it yet. My caster form bar mirrors my moonkin form bar. When this is the case, hotkeys show fine. It seems like we're reading the caster bar (the base hotbar) and not the moonkin form bar. I'll have to get one of the guys who is much better at the core stuff to take a look at it.

**Comment by EloneSK** [comment]
> I've been able to replicate the issue, but don't have a fix for it yet. My caster form bar mirrors my moonkin form bar. When this is the case, hotkeys show fine. It seems like we're reading the caster bar (the base hotbar) and not the moonkin form bar. I'll have to get one of the guys who is much better at the core stuff to take a look at it.

great, thank you for your understanding and help.  We will wait for the repair.

**Comment by exodus444** [comment]
> I've been able to replicate the issue, but don't have a fix for it yet. My caster form bar mirrors my moonkin form bar. When this is the case, hotkeys show fine. It seems like we're reading the caster bar (the base hotbar) and not the moonkin form bar. I'll have to get one of the guys who is much better at the core stuff to take a look at it.

There is also often a problem with '-' and '=' hotkeys not showing up for multiple classes. Hard to replicate, but seeing it every once in a while.

Here's an example (binding is set via the blizzard UI, ACTIONBUTTON12 - it should be showing '=', but it's not):

![image](https://user-images.githubusercontent.com/158017/106581970-c0652380-6543-11eb-87b1-4f3133fd692d.png)

GetBindingKey("ACTIONBUTTON12") returns correctly '='.

**Comment by exodus444** [comment]
Looks to me like this logic is incorrect:

`  local PreviousBarIndex = mathfloor(ActionSlot / 12)
  local BarIndex = mathceil(ActionSlot / 12)
  local ActionSlotOffset = PreviousBarIndex * 12
  local BarSlot = ActionSlot - ActionSlotOffset
`
floor(11/12) = 0, floor(12/12) = 1, 
ceil(11/12) = 1,   ceil(12/12) = 1

As a result, for the ActionSlot 12 we get BarIndex = 1, BarSlot = 0 and obviously there is no such slot, so keybinding is missing.

**Comment by exodus444** [comment]
Possible fix HeroLib/Events/Action.lua:109

![image](https://user-images.githubusercontent.com/158017/106585816-091edb80-6548-11eb-8053-f4aa64f8fbfe.png)

**Comment by exodus444** [comment]
Yeah, fix is working:

![image](https://user-images.githubusercontent.com/158017/106585720-edb3d080-6547-11eb-91b7-7276931945f9.png)

**Comment by RussellAnas** [comment]
Let me know when this is deployed, I'll download from here and verify as well

**Comment by Cilraaz** [comment]
This change did not affect anything in my testing. If the button is removed from the base action bar, the hotkey does not show on the shifted action bar.

Edit: I did push this in commit https://github.com/herotc/hero-lib/commit/d8e79e904ddfb793f6d5d0bed078d69a48e89b0b as a fix for the ActionButton12 issue. However, it does not fix the issue that occurs with stance paging.

**Comment by exodus444** [comment]
It's a different issue then. The fix above is for the actions located on every 12th button of the bar not showing up the keybind.

**Comment by RussellAnas** [comment]
So any update on the keybinds issue for Druid? Will it be getting fixed?

**Comment by Cilraaz** [comment]
This issue should now be resolved in version 9.0.2.29. Closing this issue. If it's still a problem, please comment and I'll reopen it.
