### ISSUE TITLE
[Balance Druid] Keybinds

### ISSUE THREAD

**Issue by Lespindagger** [herotc/hero-rotation#725]
Keybinds still do not display correctly. I reinstalled entire HeroRotation, HeroLib and HeroDBC and it still displays incorrect keybinds

**Comment by Cilraaz** [comment]
What hotbar addon (if any) are you using?

**Comment by Lespindagger** [comment]
No hotbar addon. Originally had Bindpad and or Bartender4  but removed it to check if that was the cause of the issue.

**Comment by Cilraaz** [comment]
Please try version 9.0.2.30 and let me know if it's still a problem.

**Comment by Lespindagger** [comment]
Regardless of where you place spells on any keybind, the keybinds are set to a specific set of keys for a specific set of spells

**Comment by Lespindagger** [comment]
I switched spells per keybind and or keybinds to related spells per keybind, but the problem persists. Spells are set to specific set of keys for a specific set of spells.

**Comment by Lespindagger** [comment]
Tried version 9.0.2.30 and it didn't work. Reinstalled the entire HeroRotation, HeroLib and HeroDBC and it is still not displaying the correct keybinds.

**Comment by Cilraaz** [comment]
I'll need actual information. 

- You stated that you were using Blizzard's default hotbars. Is that still the case? 
- Is it showing no keybind or an incorrect keybind while in caster form or moonkin form?
- What hotkey _should_ it show?
- What hotkey _does_ it show?
- Have you done anything to modify hotbar paging?
- Is the spell in question on any other hotbar?

**Comment by Lespindagger** [comment]
Its the Blizzards default bar that I am using. Keybinds display incorrectly in Moonkin form. Regardless of hotkey, the hotkeys are preset to a default number per spell, so when one shifts any spell around the Keybinds display wrong spell. Hotbar is at its default state. All spells used for Moonkin do no set correctly unless setup in a specific order preset by HeroRotation. If you try to shift them or switch them around, the display on HeroRotation continues to display a Spell intended by the rotation but not the keybound spell set on the hotbar. That goes for both the spell displayed and the keybind number. Paging is set at #1 and its default state. Druid HeroRotation is preset both on keybind and spell icon to someones original keypattern and or keybinds. It doesn't allow to have spells shifted on the hotbars and or follow someone else's keybinds.

**Comment by Cilraaz** [comment]
What version of HeroLib are you using?

**Comment by Lespindagger** [comment]
I am using HeroLib-9.0.2.10. As previously mentioned, I reinstalled twice all elements including HeroLib

**Comment by Cilraaz** [comment]
Please try HeroRotation version 9.0.2.31 and HeroLib version 9.0.2.11. I've made a few changes that _should_ fix this issue.

**Comment by Lespindagger** [comment]
Reinstalled the entire HeroRotation, HeroLib and also HeroDBC with the new ones you have suggested but it does the same thing. Now the Celestial Aligment icon has been replaced by the Trinket icon instead and the trinket is not suggested anymore when it is off CD.

**Comment by Lespindagger** [comment]
CA/Inc is suggested but not with the proper Icon. Instead, the CA/Inc. has the trinket (whatever trinket is on the keybinds) icon. The trinket/Inc is no longer suggested or displayed with any icon or even displayed entirely.

**Comment by Cilraaz** [comment]
I am unable to replicate this.

**Comment by Lespindagger** [comment]
I moved the trinket display to the "SuggestedRight" and now the trinket displays properly and when off CD, but the CA/Inc is not displaying off CD. The original issue on Keybinds, Spell Icons and or Spell location on hotbar still persists. I am going to move the CA/inc and Trinket issue to the new issue created for it. I will continue with the Druid/Hotbar(spell keybind) issue on this one

**Comment by Lespindagger** [comment]
Ok.. now we are getting somewhere. I replaced this:

  -- We return the first match as this moment
  local ActionSlot = ActionSlots[1]
 with this:

  -- If stealthed Rogue or form-shifted Druid, return last slot. Otherwise, return the first.
  local ActionSlot
  if (GetBonusBarOffset() > 0 and (Cache.Persistent.Player.Class[1] == "Rogue" or Cache.Persistent.Player.Class[1] == "Druid")) then
    ActionSlot = ActionSlots[#ActionSlots]
  else
    ActionSlot = ActionSlots[1]
  end

as per your fix on HeroLib/Events/Action.lua now DRUID icons, spells, keybinds are FIXED!!!.. seems the download from the website and from curseforge is corrupt.

**Comment by RussellAnas** [comment]
This issue is back :(. Keybinds are all over the place on my Balance Druid.

**Comment by Lespindagger** [comment]
If you updated recently from curseforge, the update may have been corrupted. I did a manual fix.

**Comment by Cilraaz** [comment]
HeroLib 9.0.2.12 will include the fix to suggest the last ActionSlot, rather than the first, when using paging on a Druid/Rogue.

**Comment by Cilraaz** [comment]
No reports of further issues in over 2 weeks. Closing this issue.
