### ISSUE TITLE
[SV Hunter] Lua-Error

### ISSUE THREAD

**Issue by Exo62** [herotc/hero-rotation#866]
hello, i have a problem with the hero rotation with the survival hunter. almost every time i start a fight a lua error window appears with the message:

Message: Interface\AddOns\HeroRotation_Hunter\Survival.lua:328: attempt to compare number with nil
Time: Sat May  7 18:22:46 2022
Count: 695
Stack: Interface\AddOns\HeroRotation_Hunter\Survival.lua:328: attempt to compare number with nil

Locals: 

I don't know how to fix this, the addon is up to date and the error has only recently appeared. I hope you can help me.

**Comment by Cilraaz** [comment]
This has been fixed as of commit https://github.com/herotc/hero-rotation/commit/400bb3a2ea8df54b73060b13fca5ebbbd6a357f2

I'll push a new release version now, which will contain the fix.

**Comment by Cilraaz** [comment]
The fix is in release version 9.2.0.19.

**Comment by Exo62** [comment]
Thank you very much :)

**Comment by Exo62** [comment]
I exchanged the file but unfortunately the problem persists :(

**Comment by Cilraaz** [comment]
Please provide the lua error in its entirety.

**Comment by Exo62** [comment]
> Please provide the lua error in its entirety.

Message: Interface\AddOns\HeroRotation_Hunter\Survival.lua:328: attempt to compare number with nil
Time: Sat May  7 20:47:28 2022
Count: 353
Stack: Interface\AddOns\HeroRotation_Hunter\Survival.lua:328: attempt to compare number with nil

Locals:

**Comment by Cilraaz** [comment]
Please include the remainder of the lua error, specifically the Locals.

**Comment by Exo62** [comment]
> Please include the remainder of the lua error, specifically the Locals.

where can i find that? I'm sorry to cause so much trouble, I'm not familiar with it

**Comment by Cilraaz** [comment]
It should be in the same box where you pulled the base error.

**Comment by Exo62** [comment]
> It should be in the same box where you pulled the base error.

i copied everything that was in there. there is not more information

**Comment by Cilraaz** [comment]
What version of the addon are you using?

**Comment by Cilraaz** [comment]
Also, which trinkets are you using?

**Comment by Exo62** [comment]
Curseforge sais "HeroRotation-9.2.0.18.zip but inside the folder i changed everything with the 9.2.0.19 version

**Comment by Exo62** [comment]
> Also, which trinkets are you using?

overcharged anima battery and Inscrutable Quantum Device

**Comment by Cilraaz** [comment]
CurseForge has version 9.2.0.19 [on their site](https://www.curseforge.com/wow/addons/herorotation/files/3783012). Just to be sure that all files are up to date, please update with that version however you usually update addons.

**Comment by Exo62** [comment]
> CurseForge has version 9.2.0.19 [on their site](https://www.curseforge.com/wow/addons/herorotation/files/3783012). Just to be sure that all files are up to date, please update with that version however you usually update addons.

i reinstalled curseforge just to point that out but now it wont open anymore and will be stuck at the " forging your library" screen. give me a minute

**Comment by Exo62** [comment]
> CurseForge has version 9.2.0.19 [on their site](https://www.curseforge.com/wow/addons/herorotation/files/3783012). Just to be sure that all files are up to date, please update with that version however you usually update addons.
![hr](https://user-images.githubusercontent.com/105121889/167269553-43d8b7b2-a680-4804-bc3d-9fca04ebe9b9.PNG)

i reinstalled everything and took your link to install herorotation. it still says its on 9.2.0.18 and the error continues to appear randomly

**Comment by Exo62** [comment]
What also surprises me is that since the error has occurred, the "serpent bite" the next favorite action would be displayed for every single target fight. in multi taget fight it works.

**Comment by sekaone** [comment]
i had the same with serpent bite. now it only shows me bomb sometimes but most of the time just Pooling

**Comment by Cilraaz** [comment]
9.2.0.18 has a known issue. It looks like Curse is having some website issues. Once they're sorted out and you update to 9.2.0.19, please retry and see if you have the same issue. Alternatively, please manually install from the [github zip](https://github.com/herotc/hero-rotation/releases/download/9.2.0.19/HeroRotation-9.2.0.19.zip).

**Comment by Exo62** [comment]
> 9.2.0.18 has a known issue. It looks like Curse is having some website issues. Once they're sorted out and you update to 9.2.0.19, please retry and see if you have the same issue. Alternatively, please manually install from the [github zip](https://github.com/herotc/hero-rotation/releases/download/9.2.0.19/HeroRotation-9.2.0.19.zip).

i will try that. thank you and i will reply wen its updated

**Comment by Cilraaz** [comment]
No updates in 6 days. If this is still an issue, please let us know.
