### ISSUE TITLE
[Bug]: Destruction Warlock Rotation is completely off (Channel Demonfire/OpenerRotation/CappingSoulShards)

### ISSUE THREAD

**Issue by Soulsmacka** [herotc/hero-rotation#948]
### What version of HeroRotation are you using?

10.1.0.08

### What version of HeroLib are you using?

10.1.0.03

### What version of HeroDBC are you using?

10.1.0.01

### What is the issue?

The opening cast sequence is completely off. it should be:

Pre-cast Incinerate.
Pre-cast Immolate.
Cast Summon Infernal.
Use your trinkets and racial
Cast Conflagrate.
Cast Chaos Bolt.
Cast Conflagrate.
Cast Chaos Bolt.
Cast Channel Demonfire.

 So that's first. Then Channel Demonfire doesn't show up as a suggestion for single target which it should especially since our tier-set bonuses rely on it. Then when it's an AoE situation, Channel Demonfire is suggested but it's not available to use. This might have been fixed with this latest update because it was happening at the start of an AoE pack pull with the standard 3 soul shards. Now it actually suggests using Demonfire at the correct time, but when Demonfire comes off of cooldown, it doesn't suggest it again if the fight last long enough to use it more than once. 

I've used your addon for years so doing exactly what it suggests even on hectic fights isn't really an issue for me. 

So one thing that I've noticed after logging my combat and analyzing it using Warcraft logs and wowanalyzer.com is that I'm capping soul shards a lot and not casting Demonfire off of CD. Here is the report on a single-target fight: 

https://wowanalyzer.com/report/w2hHvQ7rWtjbJg3F/2-Normal+Kazzara,+the+Hellforged+-+Kill+(3:28)/Psyl%C3%B8ck/standard

This is the build used for that fight:

BsQA+63P9mnDJYMkogOeTUhr8CIJRSCkmCRaJJhUCcgElkE5AEaFSCAAAAAAAAAAAggkSSkA

Please overhaul this rotation file completely when possible. Thanks. 

### Icon Behavior

N/A

**Comment by Cilraaz** [comment]
The APL does not contain a specialty opener rotation. As such, neither do we.

There are multiple conditions under which Channel Demonfire will show up in single target.

There was a coding error causing Channel Demonfire to show up when it was not usable. This is fixed in commit https://github.com/herotc/hero-rotation/commit/0cd3374569ca09894d445eb658c674ac15bc87d6

There was also an error with the ID of the Conflagrate debuff, causing the check against that debuff to always fail. With this fixed, Channel Demonfire should be suggested _much_ more often. This is fixed in commit https://github.com/herotc/hero-rotation/commit/a156b016c26c40520bcf585ef6178a8fdd94be63

These changes should resolve the issues you were seeing with Channel Demonfire.

**Comment by Soulsmacka** [comment]
> The APL does not contain a specialty opener rotation. As such, neither do we.
> 
> There are multiple conditions under which Channel Demonfire will show up in single target.
> 
> There was a coding error causing Channel Demonfire to show up when it was not usable. This is fixed in commit [0cd3374](https://github.com/herotc/hero-rotation/commit/0cd3374569ca09894d445eb658c674ac15bc87d6)
> 
> There was also an error with the ID of the Conflagrate debuff, causing the check against that debuff to always fail. With this fixed, Channel Demonfire should be suggested _much_ more often. This is fixed in commit [a156b01](https://github.com/herotc/hero-rotation/commit/a156b016c26c40520bcf585ef6178a8fdd94be63)
> 
> These changes should resolve the issues you were seeing with Channel Demonfire.

How do I fix (update) this? It's still not working for me and now, for whatever reason, this version makes the spells disappear for a bit.  I uninstalled the newest version and reinstalled and it still doesn't work.

Edit: Sumon Infernal is making the addon not show what rotation to press. Once he expires, the addon starts working Again. I will submit a new bug report

**Comment by Soulsmacka** [comment]
I went into the actual lua files and pasted the new lua string to overwrite the old files in destruction.lua and warlock.lua and it doesnt work. The addon just doesnt activate on my warlock at all. Had to reinstall to fix

**Comment by Cilraaz** [comment]
Then the copy/paste was done incorrectly.

**Comment by Soulsmacka** [comment]
> Then the copy/paste was done incorrectly.

I copied the entire string (fully expanded) deleted all the old code off the file, and hit control v to make sure no old code was there and saved it.

Should I update the destruction.lua, the warlock.lua and the overide.lua?  

Or maybe just push out a new update with the new code? (including the summon infernal bug fix)

**Comment by Cilraaz** [comment]
You would need to update all 3 files.

**Comment by Soulsmacka** [comment]
> The APL does not contain a specialty opener rotation. As such, neither do we.
> 
> There are multiple conditions under which Channel Demonfire will show up in single target.
> 
> There was a coding error causing Channel Demonfire to show up when it was not usable. This is fixed in commit [0cd3374](https://github.com/herotc/hero-rotation/commit/0cd3374569ca09894d445eb658c674ac15bc87d6)
> 
> There was also an error with the ID of the Conflagrate debuff, causing the check against that debuff to always fail. With this fixed, Channel Demonfire should be suggested _much_ more often. This is fixed in commit [a156b01](https://github.com/herotc/hero-rotation/commit/a156b016c26c40520bcf585ef6178a8fdd94be63)
> 
> These changes should resolve the issues you were seeing with Channel Demonfire.

**Comment by Soulsmacka** [comment]
> You would need to update all 3 files.

I did all 3. Didn't work still. I guess I will wait for an update to be available on curse forge.

**Comment by Soulsmacka** [comment]
> The APL does not contain a specialty opener rotation. As such, neither do we.
> 
> There are multiple conditions under which Channel Demonfire will show up in single target.
> 
> There was a coding error causing Channel Demonfire to show up when it was not usable. This is fixed in commit [0cd3374](https://github.com/herotc/hero-rotation/commit/0cd3374569ca09894d445eb658c674ac15bc87d6)
> 
> There was also an error with the ID of the Conflagrate debuff, causing the check against that debuff to always fail. With this fixed, Channel Demonfire should be suggested _much_ more often. This is fixed in commit [a156b01](https://github.com/herotc/hero-rotation/commit/a156b016c26c40520bcf585ef6178a8fdd94be63)
> 
> These changes should resolve the issues you were seeing with Channel Demonfire.

Without getting the updated file, I noticed that the rotation addon only suggests Channel Demonfire when Avatar of Destruction is procced and we have the Blasphemy buff active. I hope the fix allows channel demonfire to be used on cooldown because I don't see a damage increase modifier (or need to wait) on waiting to cast Channeled Demonfire when the Blasphemy debuff is active.

**Comment by Cilraaz** [comment]
The highest priority usage of Channel Demonfire in single target is when Raging Demonfire is talented and Immolate/Conflagrate debuffs are active. This is where the Conflagrate debuff ID was coded incorrectly. Once that update is applied, Channel Demonfire will be suggested much more often.

**Comment by Cilraaz** [comment]
You can download the up to date zip from [here](https://github.com/herotc/hero-rotation/archive/refs/heads/dragonflight.zip), grab the Warlock.lua, Overrides.lua, and Destruction.lua files from the HeroRotation_Warlock folder, and paste them into your current addon folder. That will give you the updates.

**Comment by Soulsmacka** [comment]
> You can download the up to date zip from [here](https://github.com/herotc/hero-rotation/archive/refs/heads/dragonflight.zip), grab the Warlock.lua, Overrides.lua, and Destruction.lua files from the HeroRotation_Warlock folder, and paste them into your current addon folder. That will give you the updates.

This helped out and it's definitely updated. Only thing left is to fix the bug when Infernal is active, the addon goes blank which I opened up a seperate ticket for. Thanks for the quick response and willingness to fix quickly. Greatly Appreciated.

**Comment by Cilraaz** [comment]
I replied to that ticket requesting more information.
